#!/usr/bin/env bash
#This script displays numbers from 1-100 but displays FizzBuzz, Fizz, and Buzz for multiples of 3 and 5, multiples of 3 and multiples of 5 respectively

for (( i=1; i < 101; i++ ))
do
    if (( i % 15 == 0 )); then
	echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
	echo "Fizz"
    elif (( i % 5 == 0 )); then
	echo "Buzz"
    else
	echo "$i"
    fi
done
