#!/usr/bin/env bash
# This script displays hours from 0-12 and all the 59 minutes
h=0
while [ "$h" -le 12 ]
do
    echo "Hour: $h"
    (( h++ ))

    m=1
    while [ "$m" -le 59 ]
    do
	echo "$m"
	(( m++ ))
    done
done
