#!/usr/bin/env bash
# This script displays the content of the current directory in list format and only displays the the part of the name after the first dash

file="school"

if [ -e "$file" ]; then
    echo "$file file exists"

    if [ -s "$file" ]; then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi

    if [ -f "$file" ]; then
	echo "$file is a regular file"
    fi

else
    echo "$file file does not exist"
fi
