#!/usr/bin/env bash
# This script creates a file with its PID and displays 'To infinity and beyond' indefinitely, 
'I hate the kill command' when receving a SIGTERM signal, 'Y U no love me?!' when receiving a SIGINT signal and deletes the initial file on a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"

echo $$ > "$file"

trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

trap 'echo Y U no love me?!' SIGINT

while :; do
    
    echo "To infinity and beyond"
    
    sleep 2
    
done
