#!/usr/bin/env bash
# This script displays 'To infinity and beyond' and 'I am invincible!!!' indefinitely with a sleep 2 in between each iteration

altmessage()
{
    echo "I am invincible!!!"
}
trap "altmessage" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
